#testing code for tiny compiler

all:
	@gcc recursive_descent_if.c -o recursive_descent_if
	@gcc recursive_descent_calc.c -o recursive_descent_calc
clean:
	@rm -rf recursive_descent_if recursive_descent_calc
